### ISSUE TITLE
Detect cases when one of system users has wrong DTYPE

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-old#214]
See forum topic: https://www.cuba-platform.com/discuss/t/the-application-dont-launch-after-extending-entity-user-and-user-edit-screen/11274

Developer has assigned wrong DTYPE value to entries in sec_user table.

This case is so common (I think I have seen it dozen times on the forum) and so disastrous that I think we should detect it on server start and write detailed explanation message to the log.

That is: if user with (cuba.jmxUserLogin) or anonymous user can't be loaded from the database - try to execute native SQL:
> select DTYPE from SEC_USER where ...

Compare returned DTYPE value with the value of the extended ext$User entity.

**Comment by knstvk** [comment]
Not relevant anymore as we generate User entity in the project and extension is not needed.
