### ISSUE TITLE
Make @ModelObject annotation optional

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-old#348]

**Comment by aleksey-stukalov** [comment]
Simple POJOs with no annotations should work just fine - the only requirement should be implementing the `JmixEntity` interface. To exclude unnecessary fields devs can use the `@SystemLevel` annotation, which is implemented exactly for this purpose (see javadocs).

**Comment by knstvk** [comment]
`@ModelProperty` has been made optional in #574.
Regarding `@ModelObject` - will decide later, as on one hand there are difficulties with enhancing of classes having parents in other module, on the other hand - an annotation describing the class purpose (`@Component`, `@Entity`) is a usual practice.
