### ISSUE TITLE
Dynamic attributes usage in Entity Log

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-old#448]
Log dynamic attributes as usual attributes

- [x] Implement tests for dynamic attributes logging
- [x] Propose `dynattr`-`audit` interaction model
- [x] Implement diff calculation and JpaDataStoreListener#onEntityChange invocation on dynamic attribute changes
- [x] Implement logging for UPDATE
- [x] Implement logging for CREATE
- [x] Implement logging for DELETE
- [x] Embedded entity extra state changes?
- [x] Update according to master changes, refactor
 
**QA Notes:**

**Requirements**
- use postgres or other database that can be acessed manually
or
- wait until Haulmont/jmix-ui#302 will be fixed

**Steps:**
1. Create project 
2.     add dynattr and audit addons in build.gradle:

```
    implementation "io.jmix.dynattr:jmix-dynattr-starter"
    implementation "io.jmix.dynattr:jmix-dynattr-ui-starter"

    implementation "io.jmix.audit:jmix-audit-starter"
    implementation "io.jmix.audit:jmix-audit-ui-starter"

```
3. Create some entity and screens: editor and browser,
4. add `<dynattrui:dynamicAttributes/>` facets to screens
5. run application and setup dynamic attributes, 
6. setup audit including dynamic attribute,
7. create/modify entities.
**ER:**
- Selected dynamic attributes logged (see it in Entity Log screen if Haulmont/jmix-ui#302 fixed or in `audit_entity_log` table in database)

**Comment by owlet1997** [comment]
incorrect text of notification about applying changes after creating dynamic attribute:
![image](https://user-images.githubusercontent.com/45730069/107741438-98857500-6d26-11eb-96dc-197e0234fefe.png)

**Comment by owlet1997** [comment]
if instance was created with dynamic attribute of type boolean and value was 'false', after deleting this instance without updating this attribute is empty in the right table:
![image](https://user-images.githubusercontent.com/45730069/107742297-375ea100-6d28-11eb-98ce-802b6644439c.png)
 ER: this attribute is not empty and value is 'false'

**Comment by owlet1997** [comment]
creating entities
![image](https://user-images.githubusercontent.com/45730069/107758065-ccb95f80-6d3f-11eb-9bda-714bc225a4ec.png)
![image](https://user-images.githubusercontent.com/45730069/107758143-ea86c480-6d3f-11eb-9833-fcb7726f914f.png)

**Comment by dtaimanov** [comment]
There are separate ticket for this bug: https://github.com/Haulmont/jmix-data/issues/43
"changesApplied" message will be fixed in that ticket too
