### ISSUE TITLE
ListEditor component support

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-old#460]
Introduce an action for the `ValuesPicker` component. See https://github.com/Haulmont/jmix-ui/issues/6.

**Comment by andreysubbotin** [comment]
Requires for Dynamic Attribute UI

**Comment by glebfox** [comment]
Splitted to:
* https://github.com/haulmont/jmix-cuba/issues/2
* https://github.com/Haulmont/jmix-ui/issues/13
